[Primary]
dev = "ens19"

[Backup]
dev = "ens18"

[SLA]
echo = [
  "223.5.5.5",
  "114.114.114.114",
  "119.29.29.29",
]

echo_count = 1

echo_timeout = 1

echo_all_fail = 1

echo_fast_fail = 0

interval = 3

fail = 3

fast_fail = 0

recover = 5

fast_recover = 0
