[General]
#Enable debug log
debug = 0

#Enable config hot reload
hot_reload = 1

#Enable routes restore on exit
restore = 1

[Primary]
#Primary Route NIC
dev = "ens19"

[Backup]
#Backup Route NIC
dev = "ens18"

[Probe]
#Addresses for ping
address = ["dns.aliyun.com:443", "119.29.29.29"]
#eg. address = ["223.5.5.5:80", "119.29.29.29"]
#eg. address = ["192.100.100.100","192.100.100.101"]

#DNS servers
dns = ["223.5.5.5","119.29.29.29", "1.1.1.1"]

#Number of pings
count = 1

#Seconds of ping timeout
timeout = 1

#Delay seconds between probes
delay = 3

#Number of DOWN probes to switch to Backup route
down = 3

#Strategy of probes mark DOWN (0: Passive 1: Positive)
down_strategy = 1

#Failover to Backup route quickly on DOWN
fast_failover = 0

#Number of UP Probes to switch back to Primary route
up = 5

#Strategy of probes mark UP (0: Passive 1: Positive)
up_strategy = 0

#Recover to Primary route quickly on UP
fast_recover = 0
